### ISSUE TITLE
namespace invalid argument

### ISSUE THREAD

**Issue by silverfox983** [dint-dev/universal_html#14] opened 2020-02-24 21:11 UTC
Not sure why I cant return the body of ebay's homepage.

`[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Invalid argument (namespace): "http://www.w3.org/1999/xlink"
E/flutter (18121): #0      Element.setAttributeNS (package:universal_html/src/html/dom/element.dart:2128:7)
E/flutter (18121): #1      _HtmlParser._newNodeFrom.<anonymous closure> (package:universal_html/src/driver/dom_parser_driver.dart:237:20)
E/flutter (18121): #2      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter (18121): #3      _HtmlParser._newNodeFrom (package:universal_html/src/driver/dom_parser_driver.dart:235:25)
E/flutter (18121): #4      _HtmlParser._newNodeFrom (package:universal_html/src/driver/dom_parser_driver.dart:248:23)
E/flutter (18121): #5      _HtmlParser._newNodeFrom (package:universal_html/src/driver/dom_parser_driver.dart:248:23)
E/flutter (18121): #6      _HtmlParser._newNodeFrom (package:universal_html/src/driver/dom_parser_driver.dart:248:23)
E/flutter (18121): #7      _HtmlParser._newNodeFrom (package:universal_html/src/driver/dom_parser_driver.dart:248:23)
E/flutter (18121): #8      _HtmlParser._newNodeFrom (package:universal_html/src/driver/dom_parser_driver.dart:248:23)
E/flutter (18121): #9      _H
I/flutter (18121): null
I/flutter (18121): `

**Comment by terrier989** [comment] 2020-02-25 08:25
Thanks for the bug report! :) The issue is now fixed (version 1.1.14).

**Closed by terrier989** 2020-02-25 08:25 UTC
